### ISSUE TITLE
帅哥，和bootstrap导航的下拉菜单冲突。

### ISSUE THREAD

**Issue by xjdata** [lichunqiang/yii2-lock-form#2]
如果在页面中包含bootstrap的nav组建，并且有下拉菜单项，那么下拉菜单点不开。

**Comment by lichunqiang** [comment]
如果你项目中使用的是 `bootstrap` 的话，请用 `light\widgets\LockBsFormAsset`

**Comment by lichunqiang** [comment]
`light\widgets\LockFormAsset`是针对项目中并没有引入 `bootstrap` 时需要依赖的。

**Comment by xjdata** [comment]
呃.... 怎么给你提的问题，都让自己觉得自己太菜了。。。 不好意思，不好意思。

**Comment by xjdata** [comment]
不过 好像你把2个的js依赖搞反了。
我看了下， lock.bootstrap.js 是你在 LockFormAsset.php 中设置的。

**Comment by lichunqiang** [comment]
- -! 好吧，下个版本换一下，不过不会影响使用

**Comment by xjdata** [comment]
恩。 呵呵。 多谢~
