### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by yangqi93** [lichunqiang/yii2-lock-form#5]
Hi, lichunqiang

In the README.md, I see `$ composer require light\yii2-lock-form=~1.0.2`,
but when I excute this command, there has an error 
"Problem 1
    - The requested package lightyii2-lock-form could not be found in any version, there may be a typo in the package name.
"

Then I change the command with `$ composer require light/yii2-lock-form=~1.0.2` that can success excute.

**Comment by lichunqiang** [comment]
Fixed. Thanks for your suggestion.~
